# Generated by Django 6.1 on 2026-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(verbose_name='توضیحات اسلایدر'),
        ),
    ]
